# package.json repo à changer

tasks:
  - name: Configuration
    before: bash .gitpod-config/globalDependencies.sh
    init: pnpm install
    command: jest
    
vscode:
  extensions:
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - graphql.vscode-graphql
    - kavod-io.vscode-jest-test-adapter
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - yatki.vscode-surround
    - bradlc.vscode-tailwindcss
    - hbenl.vscode-test-explorer
    - fabiospampinato.vscode-todo-plus
    - dbaeumer.vscode-eslint
    - codezombiech.gitignore
    - foxundermoon.shell-format
    - redhat.vscode-xml
    - hbenl.test-adapter-converter
